/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-strong": "var(--color-primary-strong)",
        secondary: "var(--color-secondary)",
        "doctor-cta": "var(--color-doctor-cta)",
        success: "var(--color-success)",
        "success-indicator": "var(--color-success-indicator)",
        orange: "var(--color-orange)",
        "orange-hover": "var(--color-orange-hover)",
        "ai-accent": "var(--color-ai-accent)",
        "healing-accent": "var(--color-healing-accent)",
        surface: {
          app: "var(--color-surface-app)",
          default: "var(--color-surface-default)",
          muted: "var(--color-surface-muted)",
          subtle: "var(--color-surface-subtle)",
          raised: "var(--color-surface-raised)",
          success: "var(--color-surface-success)",
          "blue-light": "var(--color-surface-blue-light)",
          "chat-ai": "var(--color-surface-chat-ai)",
          "success-badge": "var(--color-surface-success-badge)",
          "doctor-badge": "var(--color-surface-doctor-badge)",
        },
        text: {
          primary: "var(--color-text-primary)",
          heading: "var(--color-text-heading)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          form: "var(--color-text-form)",
          ai: "var(--color-text-ai)",
          chat: "var(--color-text-chat)",
          "role-secondary": "var(--color-text-role-secondary)",
          "search-placeholder": "var(--color-text-search-placeholder)",
          "otp-helper": "var(--color-text-otp-helper)",
          "ai-supporting": "var(--color-text-ai-supporting)",
          "chat-timestamp": "var(--color-text-chat-timestamp)",
          "chat-placeholder": "var(--color-text-chat-placeholder)",
        },
        border: {
          default: "var(--color-border-default)",
          subtle: "var(--color-border-subtle)",
          surface: "var(--color-border-surface)",
          primary: "var(--color-border-primary)",
          success: "var(--color-border-success)",
          chat: "var(--color-border-chat)",
          doctor: "var(--color-border-doctor)",
          "focus-otp": "var(--color-border-focus-otp)",
        },
      },
      backgroundImage: {
        "gradient-primary": "var(--color-primary-gradient)",
        "gradient-ai": "var(--color-ai-gradient)",
        "gradient-teal": "var(--color-teal-gradient)",
        "gradient-healing-panel": "var(--color-healing-panel-gradient)",
        "gradient-ai-panel": "var(--color-ai-panel-gradient)",
      },
      fontFamily: {
        body: "var(--font-family-body)",
        chat: "var(--font-family-chat)",
        otp: "var(--font-family-otp-display)",
      },
      fontSize: {
        "body-xs": ["var(--font-size-body-xs)", { lineHeight: "var(--line-height-body)" }],
        "body-sm": ["var(--font-size-body-sm)", { lineHeight: "var(--line-height-body)" }],
        body: ["var(--font-size-body)", { lineHeight: "var(--line-height-body)" }],
        "body-lg": ["var(--font-size-body-lg)", { lineHeight: "var(--line-height-body)" }],
        "body-xl": ["var(--font-size-body-xl)", { lineHeight: "var(--line-height-body)" }],
        label: ["var(--font-size-label)", { lineHeight: "var(--line-height-body)" }],
        "label-lg": ["var(--font-size-label-lg)", { lineHeight: "var(--line-height-body)" }],
        button: ["var(--font-size-button)", { lineHeight: "var(--line-height-button)" }],
        "button-lg": ["var(--font-size-button-lg)", { lineHeight: "var(--line-height-button)" }],
        "heading-sm": ["var(--font-size-heading-sm)", { lineHeight: "var(--line-height-body)" }],
        "heading-md": ["var(--font-size-heading-md)", { lineHeight: "var(--line-height-body)" }],
        "heading-lg": ["var(--font-size-heading-lg)", { lineHeight: "var(--line-height-body)" }],
        "heading-xl": ["var(--font-size-heading-xl)", { lineHeight: "var(--line-height-body)" }],
        display: ["var(--font-size-display)", { lineHeight: "var(--line-height-body)" }],
        "ai-hero": ["var(--font-size-ai-hero)", { lineHeight: "var(--line-height-body)" }],
        otp: ["var(--font-size-otp)", { lineHeight: "var(--line-height-otp)" }],
      },
      fontWeight: {
        body: "var(--font-weight-body)",
        label: "var(--font-weight-label)",
        button: "var(--font-weight-button)",
        heading: "var(--font-weight-heading)",
        display: "var(--font-weight-display)",
      },
      lineHeight: {
        standard: "var(--line-height-standard)",
        body: "var(--line-height-body)",
        button: "var(--line-height-button)",
        otp: "var(--line-height-otp)",
        normal: "var(--line-height-normal)",
      },
      letterSpacing: {
        body: "var(--letter-spacing-body)",
      },
      spacing: {
        "component-xs": "var(--space-component-xs)",
        "component-sm": "var(--space-component-sm)",
        "component-md": "var(--space-component-md)",
        "component-lg": "var(--space-component-lg)",
        "component-xl": "var(--space-component-xl)",
        section: "var(--space-section)",
        layout: "var(--space-layout)",
        "page-inline": "var(--space-page-inline)",
        "header-block": "var(--space-header-block)",
        "sidebar-block": "var(--space-sidebar-block)",
        "sidebar-group": "var(--space-sidebar-group)",
        "search-padding": "var(--space-search-padding)",
        "search-gap": "var(--space-search-gap)",
        "nav-gap": "var(--space-nav-gap)",
        "nav-icon-text": "var(--space-nav-icon-text)",
        "card-padding": "var(--space-card-padding)",
        "activity-icon-content": "var(--space-activity-icon-content)",
        "otp-cell-gap": "var(--space-otp-cell-gap)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        round: "var(--radius-round)",
        pill: "var(--radius-pill)",
        "chat-bubble": "var(--radius-chat-bubble)",
      },
      borderWidth: {
        DEFAULT: "var(--border-width)",
        otp: "var(--border-width-otp)",
        chat: "var(--border-width-chat)",
        doctor: "var(--border-width-doctor)",
      },
      boxShadow: {
        search: "var(--elevation-search)",
        card: "var(--elevation-card)",
        input: "var(--elevation-input)",
        activity: "var(--elevation-activity)",
        doctor: "var(--elevation-doctor)",
        hero: "var(--elevation-hero)",
        "ai-message": "var(--elevation-ai-message)",
      },
    },
  },
  plugins: [],
};
